#!/bin/bash
#$ -pe smp 4
#$ -l h_vmem=32G
#$ -l h_rt=1:0:0
#$ -cwd
#$ -t 1-10
#$ -o job_output/
#$ -e job_errors/


# Make list of bam files generated by star alignment

#find results/star_alignment | grep ".bam" > assets/lists/bam_list.txt

module load samtools

SAMPLE=$(sed -n "${SGE_TASK_ID}p" assets/lists/bam_list.txt)
OUTPUT_PATH="results/star_alignment/$(basename "$SAMPLE").bai"

samtools index "$SAMPLE" "$OUTPUT_PATH"